import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Head
import Head from "./head";

// Components
import Header from "../components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Filipinho",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Head />
      <body className="w-full font-roboto bg-secondary">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
